version: '3'

services:
  spring-boot-rest-api-app:
    image: solution-b-api-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - /data/spring-boot-app